### ISSUE TITLE
bug: long response from `:BackseatAsk` does not wrap on display box

### ISSUE THREAD

**Issue by luiz00martins** [james1236/backseat.nvim#10]
When displaying the answer from `:BackseatAsk`, the UI box seems to not wrap the text, instead seemingly continuing outside of the screen. As an example:

![image](https://user-images.githubusercontent.com/43142209/230217325-3204947c-bb7d-4731-9e5c-9cf2f77e1581.png)

I imagine the phrase continues after "`open buffers, window layouts, and`", however, it got cut off.

**Comment by james1236** [comment]
Fixed in d88695edc363e40885e1a46f8ad3f5cf2ada053b!

**Comment by luiz00martins** [comment]
Still broken on my end:
![image](https://user-images.githubusercontent.com/43142209/230222481-15e03d01-dd42-4c72-b421-fe2e48e608c9.png)

_(Worth to note the "`temporarilyenable`" and "`searchfeature`". They probably point to the issue.)_

**Comment by james1236** [comment]
Are you using windows? Maybe this is a \n vs \r\n issue since it works for me.
![image](https://user-images.githubusercontent.com/32351696/230223684-846446dc-0f5c-46ed-b16f-5686aa8a8c43.png)

**Comment by luiz00martins** [comment]
Yep! I'm on windows.

**Comment by james1236** [comment]
It shouldn't make a difference, since I use \n to split virtual text feedback lines and I assume that works for you, but I have changed BackseatAsk output to use \r\n. Maybe try now? (image unrelated)

![image](https://user-images.githubusercontent.com/32351696/230225094-aecde8fb-369b-4406-a996-6cb774ffbfc3.png)

**Comment by luiz00martins** [comment]
Found the issue. It turns out it's not a `backseat.nvim` issue at all, but a `noice.nvim` one.

This is the MWE config:
```lua
using {
	'james1236/backseat.nvim',
	config = function()
		require('backseat').setup()
	end,
}

using {
	'folke/noice.nvim',
	dependencies = {
		'MunifTanjim/nui.nvim',
		'rcarriga/nvim-notify',
	},
	config = function()
		require('noice').setup()
	end,
}
```

This will produce the odd cut-off.

May I ask you what exactly you are using to display the text, so I may open an issue to `noice`? (or you can open it yourself, if you wish!)

**Comment by james1236** [comment]
I am using `vim.fn.confirm`, thanks for figuring it out!
